CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS contact_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, email VARCHAR(254) NOT NULL, phone VARCHAR(30) NOT NULL, message VARCHAR(2500) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS contact_messages_created_at_idx ON contact_messages (created_at DESC);
CREATE TABLE IF NOT EXISTS services (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(160) NOT NULL, description VARCHAR(3000) NOT NULL, category VARCHAR(100) NOT NULL, price NUMERIC(12,2) NOT NULL CHECK (price >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS packages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(160) NOT NULL, details VARCHAR(5000) NOT NULL, price NUMERIC(12,2) NOT NULL CHECK (price >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
