import { useEffect, useState } from 'react'
import { apiClient } from '@/services/apiClient'
import { getSession } from '@/services/auth'

type Service = { id: string; title: string; description: string; category: string; price: string | number }
type TreatmentPackage = { id: string; title: string; details: string; price: string | number }
export function AdminServiceManager() {
  const [services, setServices] = useState<Service[]>([]); const [packages, setPackages] = useState<TreatmentPackage[]>([]); const [message, setMessage] = useState('Cargando catálogo…'); const token = getSession()?.token
  async function load() { try { const data = await apiClient<{ services: Service[]; packages: TreatmentPackage[] }>('/admin/services-packages', {}, token); setServices(data.services); setPackages(data.packages); setMessage('') } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible cargar el catálogo.') } }
  useEffect(() => { void load() }, [])
  async function save(kind: 'services' | 'packages', item: Service | TreatmentPackage) { const title = window.prompt('Título', item.title); if (title === null) return; const price = window.prompt('Precio', String(item.price)); if (price === null) return; try { await apiClient(`/admin/${kind}/${item.id}`, { method: 'PUT', body: JSON.stringify({ title, price }) }, token); setMessage('Guardado. La caché pública fue invalidada.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible guardar el cambio.') } }
  return <main className="admin"><div className="container"><p className="eyebrow">Administración</p><h1 className="section-title">Servicios y paquetes</h1><p className="notice">Los cambios requieren un token OAuth2 con privilegios de administrador.</p>{message && <p role="status">{message}</p>}<div className="admin-card" style={{ overflowX: 'auto' }}><h2 className="display">Servicios</h2><table className="admin-table"><thead><tr><th>Servicio</th><th>Categoría</th><th>Valor</th><th /></tr></thead><tbody>{services.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><br/><span>{item.description}</span></td><td>{item.category}</td><td>{item.price}</td><td><button type="button" className="button-gold" onClick={() => void save('services', item)}>Editar</button></td></tr>)}</tbody></table></div><div className="admin-card" style={{ overflowX: 'auto', marginTop: '1rem' }}><h2 className="display">Paquetes</h2><table className="admin-table"><thead><tr><th>Paquete</th><th>Valor</th><th /></tr></thead><tbody>{packages.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><br/><span>{item.details}</span></td><td>{item.price}</td><td><button type="button" className="button-gold" onClick={() => void save('packages', item)}>Editar</button></td></tr>)}</tbody></table></div></div></main>
}
