import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { PageHero } from '@/components/PageHero'
import { serviceCategories } from '@/data/servicesData'
import { apiClient } from '@/services/apiClient'

export function Booking() { const [searchParams] = useSearchParams(); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false); const selectedService = searchParams.get('service') || ''
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setStatus(''); const form = new FormData(event.currentTarget); try { const result = await apiClient<{ schedulingUrl: string }>('/booking/calendly', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); window.location.assign(result.schedulingUrl) } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible abrir la agenda.') } finally { setLoading(false) } }
  return <main className="page-shell"><PageHero eyebrow="Reserva tu cita" title={<>Tu valoración es el<br/><em>primer paso.</em></>}><p>Cuéntanos qué estás buscando y te llevaremos al horario disponible más adecuado.</p></PageHero><section className="section dark"><div className="booking-panel"><form onSubmit={submit}><div className="form-field"><label htmlFor="booking-name">Nombre completo</label><input id="booking-name" name="name" required minLength={2}/></div><div className="form-field"><label htmlFor="booking-email">Correo</label><input id="booking-email" type="email" name="email" required/></div><div className="form-field"><label htmlFor="booking-phone">Teléfono</label><input id="booking-phone" name="phone" required minLength={7}/></div><div className="form-field"><label htmlFor="service">Servicio de interés</label><select id="service" name="service" defaultValue={selectedService} required><option value="">Selecciona una opción</option>{serviceCategories.map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</select></div><div className="form-field"><label htmlFor="booking-note">Notas (opcional)</label><textarea id="booking-note" name="notes" rows={4}/></div><button className="button-gold" type="submit" disabled={loading}>{loading ? 'Abriendo agenda...' : 'Ver horarios disponibles'}</button><p className="form-message" role="status">{status}</p></form></div></section></main> }
