import { Link } from 'react-router-dom'
import { FloralCorner, FloralLotus } from '@/components/SvgIcons'

export function Home() { return <main className="page-shell">
  <section className="hero" style={{ '--hero-image': 'url(/services/Service2.jpg)' } as React.CSSProperties}><FloralLotus className="motif top-left"/><FloralCorner className="motif top-right"/><FloralLotus className="motif bottom-right"/><div className="hero-inner"><img className="hero-logo" src="/logoWhiteNoBg.png" alt="Majo Silvera Fisio Estetic" /><p className="eyebrow" style={{ marginTop: '1.5rem' }}>Fisioterapia · Estética · Bienestar</p><h1>Vuelve a sentirte bien <em>en tu piel.</em></h1><p>Una atención personal donde la ciencia de la fisioterapia se une al arte de la estética para devolverte vitalidad.</p><div className="hero-actions"><Link className="button-gold" to="/contacto">Contacto</Link><Link className="button-outline" to="/servicios">Ver servicios</Link></div></div></section>
  <section className="section dark"><FloralCorner className="motif top-right"/><div className="container" style={{ maxWidth: 860 }}><p className="eyebrow">Bienvenida</p><h2 className="section-title">Menos tensión.<br/><em>Mejor piel.</em></h2><div className="soft" style={{ fontSize: '1.05rem' }}><p>Aquí la ciencia de la fisioterapia se une al arte de la estética para liberar tensiones, renovar tu piel y devolverte vitalidad.</p><p>Cada protocolo nace de una valoración personalizada, porque no hay dos cuerpos iguales ni dos historias iguales.</p></div><p className="display" style={{ color: '#B8973A', fontSize: '1.35rem', lineHeight: 1.5, marginTop: '2rem' }}>“Más que un servicio, es un viaje hacia tu bienestar.”</p></div></section>
  <section className="section" style={{ background: '#252218' }}><FloralLotus className="motif top-right"/><div className="container"><p className="eyebrow">Cómo trabajamos</p><h2 className="section-title" style={{ color: '#F0EBE0' }}>Tres momentos<br/>en <em>cada plan</em></h2><div className="steps">{[['Primero','Valoración','Escuchamos tu historia y evaluamos piel, postura y tensión muscular antes de tocar nada. De ahí sale tu plan.'],['Durante','Protocolo a tu medida','Combinamos fisioterapia y estética en la dosis que tu cuerpo necesita, respetando sus tiempos de recuperación.'],['Después','Acompañamiento','Te explicamos cuidados, expectativas y cuándo volver. Registramos tu evolución sesión a sesión.']].map(([kicker,title,copy]) => <article className="step" key={title}><span className="step-kicker">{kicker}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
  <section className="section cream"><FloralCorner className="motif bottom-right"/><div className="container"><p className="eyebrow">Nuestros espacios</p><h2 className="section-title">Dos salas,<br/><em>un solo lugar</em></h2><p className="soft-dark" style={{ maxWidth: 550, marginBottom: '3rem' }}>No tienes que ir a un sitio por tu dolor de espalda y a otro por tu piel. Aquí encuentras las dos cosas.</p><div className="space-grid"><article className="space-card"><div className="image-frame"><img src="/rooms/roomPhoto1.jpeg" alt="Cabina de estética"/></div><h3>Cabina de estética</h3><p>Faciales, regenerativos y capilar.</p></article><article className="space-card"><div className="image-frame"><img src="/rooms/roomPhoto2.jpg" alt="Sala de fisioterapia"/></div><h3>Sala de fisioterapia</h3><p>Rehabilitación funcional y terapia manual.</p></article></div></div></section>
</main> }
