import { useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHero } from '@/components/PageHero'
import { serviceCategories } from '@/data/servicesData'
import { siteConfig } from '@/data/siteConfig'

export function Services() { const [activeId, setActiveId] = useState(serviceCategories[0].id); const active = serviceCategories.find((category) => category.id === activeId)!
  const colors = active.dark ? { background: '#1A1812', color: '#F0EBE0', '--line': 'rgba(240,235,224,.12)', '--muted': 'rgba(240,235,224,.55)', '--text': '#B8973A' } : { background: '#F0EBE0', color: '#1A1812', '--line': 'rgba(26,24,18,.12)', '--muted': 'rgba(26,24,18,.6)', '--text': '#1A1812' }
  return <main className="page-shell"><PageHero eyebrow="Por sesión" title={<>Servicios para cuidar<br/><em>tu bienestar.</em></>}><p>Elige una categoría para conocer tratamientos, alcance y valor por sesión.</p></PageHero><div className="service-tabs"><div className="tabs-inner">{serviceCategories.map((category) => <button type="button" className={activeId === category.id ? 'active' : ''} onClick={() => setActiveId(category.id)} key={category.id}>{category.label}</button>)}</div></div><section className="section" style={colors as React.CSSProperties}><div className="container service-layout"><div><p className="eyebrow">{active.label}</p><h2 className="section-title">{active.title}<br/><em>{active.italicTitle}</em></h2>{active.items.map((item) => <article className="service-row" key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p></div><span className="service-price">{item.price}</span></article>)}{active.note && <p style={{ color: 'var(--muted)', fontWeight: 300, lineHeight: 1.8, marginTop: '2rem' }}>{active.note}</p>}<Link className="button-gold" style={{ marginTop: '2.5rem' }} to="/contacto">Contacto</Link></div><aside className="service-aside" style={{ backgroundImage: `linear-gradient(rgba(26,24,18,.12),rgba(26,24,18,.32)),url(${siteConfig.images.therapy})` }}/></div></section></main> }
